### ISSUE TITLE
Add feature to check also if all the files in a dir appear in the tar (plus --exclude option in this direction)

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/tarchecksum#2]

**Comment by colin-nolan** [comment]
Added `check_all_files_in_directory_are_in_archive` function to enable this functionality.

**Comment by colin-nolan** [comment]
Implemented by: https://github.com/wtsi-hgi/tarchecksum/commit/2ae7285d4cc9a98e36274d922a3f39d9b5ad24aa
